import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TopMenu from "@/components/TopMenu";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProvider from "@/providers/NextAuthProvider";
import Reduxprovider from "@/redux/ReduxProvider";
import { SessionContext, SessionProvider } from 'next-auth/react';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const nextAuthSession = await getServerSession(authOptions)
  //^this from slide w10 slide21
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Reduxprovider>
        <NextAuthProvider session={ session }>
        <TopMenu/>
        {children}
        </NextAuthProvider>
        </Reduxprovider>
      </body>
    </html>
  );
}
